### ISSUE TITLE
Combine into sphinxext-opengraph?

### ISSUE THREAD

**Issue by TheTripleV** [choldgraf/sphinx-social-previews#1]
Hi,

This extension seems very cool. I noticed you added sphinxext-opengraph as a dependency. Would you want to combine this functionality into sphinxext-opengraph?

**Comment by choldgraf** [comment]
I'd be more than happy to if the maintainers of that project thought it were in scope. Where's the place to have that conversation?

Ideally, I could just delete this repository and use the opengraph extension for this functionality 👍

**Comment by TheTripleV** [comment]
Great! We do think that it would be a good addition. You can make a PR to https://github.com/wpilibsuite/sphinxext-opengraph/ . I think your `__init__.py` can mostly slot into opengraph's `__init__.py`. Swapping over to the existing title and description parsing would be the biggest change.

**Comment by choldgraf** [comment]
OK cool - I'll open up an issue over there to discuss and we can take it from there

**Comment by choldgraf** [comment]
Issue is here:

- https://github.com/wpilibsuite/sphinxext-opengraph/issues/66

**Comment by choldgraf** [comment]
closing this one in favor of a more detailed version here:

- https://github.com/choldgraf/sphinx-social-previews/issues/6

**Comment by mrocklin** [comment]
As a fly on the wall and downstream user let me just say that I'm excited about this functionality becoming more widespread

**Comment by choldgraf** [comment]
Me too!
